version: "3.7"
services:
    db:
        image: mysql:8.0
        container_name: green-tech-database
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dbgreentech
        ports:
            - "3308:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
networks:
    green-tech:
        driver: bridge
